// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKXqi20GbdtLzGu8xbQ5UpRbP-ssEcQuY',
    appId: '1:488520227610:web:9337a39d382fd63cad2aa3',
    messagingSenderId: '488520227610',
    projectId: 'cinema-project-65872',
    authDomain: 'cinema-project-65872.firebaseapp.com',
    storageBucket: 'cinema-project-65872.firebasestorage.app',
    measurementId: 'G-3FZH7H1DQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcy0Jwf-ZK_yKPAJj-9s8ZRy7tjoGggzU',
    appId: '1:488520227610:android:018d0a4348b3f5bfad2aa3',
    messagingSenderId: '488520227610',
    projectId: 'cinema-project-65872',
    storageBucket: 'cinema-project-65872.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNmKIAi0i_IXo2KFRZo5zLTvDXSSw-L8',
    appId: '1:488520227610:ios:0e42ee8717a99ae8ad2aa3',
    messagingSenderId: '488520227610',
    projectId: 'cinema-project-65872',
    storageBucket: 'cinema-project-65872.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKXqi20GbdtLzGu8xbQ5UpRbP-ssEcQuY',
    appId: '1:488520227610:web:f39fd7da449a5283ad2aa3',
    messagingSenderId: '488520227610',
    projectId: 'cinema-project-65872',
    authDomain: 'cinema-project-65872.firebaseapp.com',
    storageBucket: 'cinema-project-65872.firebasestorage.app',
    measurementId: 'G-WQ1SHCNS37',
  );
}
